// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgdqbkeydrcwmkgjwwlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZHFia2V5ZHJjd21rZ2p3d2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTg0NDgsImV4cCI6MjA3MDkzNDQ0OH0.NuOCTAh91C-bcTRkALNnSExf_fInorge9Q3SGmSqNCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});